locale = "en"
label = "English"
weight = 1
title = "XSAH"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/xsah-logott.png"
  description = "A journey from zero to DevOps engineering"


[params.author]
  name = "Sayid Amir Hosseini"
  image = "img/blowfish_logo.png"
  headline = "Learn. Build. Repeat."
  bio = "A journey from zero to DevOps engineering, driven by hands-on practice, real-world infrastructure, and continuous learning."
  links = [
    { email = "mailto:sayyidamirhosseini@gmail.com"},
    { x-twitter = "https://twitter.com/saamaed" },
    { github = "https://github.com/saamaed" },
    { linkedin = "https://www.linkedin.com/in/saamaed" },
  ]
